title: "Nam Sy Vo"
name: "Nam Sy Vo"
email: "nam@genestory.ai"

description: "AI, Genomics, Precision Medicine, Biomedical Informatics"

url: "https://namsyvo.github.io"
baseurl: ""

markdown: kramdown
theme: minima

author:
  name: "Nam Sy Vo"

collections:
  publications:
    output: true
  projects:
    output: true

plugins:
  - jekyll-feed
